// export { default as ide } from './ide';
export { default as player } from './player';
export { default as editor } from './editor';
export { default as config } from './config';
export { default as palette } from './palette';
export { default as scoreCardPaginate } from './score-card-paginate';
export { default as scoresShowView } from './scores-show-view';
export { default as modal } from './modal';
export { default as navbar } from './navbar';
export { default as youtube } from './youtube';
export { default as shots } from './shots';
export { default as judgeEffects } from './judge-effects';
export { default as sizes } from './sizes';
